main: com.esotericsoftware.dnsmadeeasy.DnsMadeEasy
---
Build.build(project);
Build.oneJAR(project);
shell("jsmoothcmd.bat " + project.path("build/DnsMadeEasy.jsmooth"));
shell("ResHacker.exe -delete build/DnsMadeEasy.exe, build/DnsMadeEasy.exe, ICONGROUP, A, 1033");
shell("ResHacker.exe -delete build/DnsMadeEasy.exe, build/DnsMadeEasy.exe, ICONGROUP, A2, 1033");
shell("ResHacker.exe -add build/DnsMadeEasy.exe, build/DnsMadeEasy.exe, build/icon.ico, ICONGROUP, MAINICON, 0");
